import React, { useState, useEffect } from 'react';
import './BullshitFact.css';

const facts = [
  "The U.S. government has spent over $1.5 trillion on a fighter jet that still doesn't work properly.",
  "Congress members can legally trade stocks based on insider information they learn in briefings.",
  "It's estimated that $138 billion in taxes go uncollected every year due to the 'tax gap'.",
  "The Pentagon failed its 6th consecutive audit in 2023 and can't account for over 60% of its assets.",
  "Pharmaceutical companies spend more on lobbying than on R&D for new drugs.",
  "The average congressional salary is $174,000, yet many members become millionaires while in office.",
  "The government pays $640 for a toilet seat and $7,600 for a coffee maker (historical Pentagon purchases).",
  "Super PACs can raise unlimited money from corporations and wealthy donors with minimal disclosure.",
  "The U.S. tax code is over 70,000 pages long - longer than the Bible, War and Peace, and the Harry Potter series combined.",
  "Congress has exempted itself from many workplace laws it imposed on private businesses.",
  "The government owns enough unused office space to fill the Empire State Building 7 times over.",
  "It costs taxpayers approximately $3.7 million per year to operate each member of Congress.",
  "Politicians can use campaign funds for personal expenses if they claim it's for 'campaign purposes'.",
  "The federal government spent $28 million studying why politicians lie (ironically).",
  "Congress members get their own private subway system under the Capitol that cost $19 million.",
  "The government once spent $1.2 million to study how to get people to stop smoking by putting graphic warning labels on cigarettes.",
  "Politicians receive automatic pay raises unless they vote to reject them (which they rarely do).",
  "Lobbyists outnumber members of Congress by a ratio of 20 to 1.",
  "The IRS spent $4 million on a single conference with themed videos and line dancing.",
  "Federal agencies spent $890,000 on a program to get millennials to eat more produce.",
  "The government paid $2 million to fund a website about romance novels.",
  "Congress exempted itself from the Affordable Care Act's insurance marketplace requirements initially.",
  "Politicians can retire with full benefits after just 5 years of service.",
  "The federal government owns over 900,000 buildings but can't keep track of what's in most of them.",
  "Congress spent $615,000 studying why chimpanzees throw poop.",
  "The government paid $387,000 to study the effects of Swedish massages on rabbits.",
  "Politicians get free parking at Washington airports while everyone else pays $25/day.",
  "The EPA paid $141,000 for one employee's 'gym membership' at a luxury fitness center.",
  "Congress members can convert leftover campaign funds to personal use when they retire.",
  "The government spent $856,000 teaching mountain lions to run on treadmills.",
  "Federal employees owe over $1.5 billion in unpaid taxes.",
  "The Senate barber shop operates at a $350,000 annual loss, subsidized by taxpayers.",
  "Politicians get free healthcare for life after serving just one term.",
  "The government paid $1.5 million to study why people don't like to read terms and conditions.",
  "Congress exempted itself from Social Security until 1984.",
  "The federal government owns 900,000 cars but has no idea where 40% of them are.",
  "Politicians can accept gifts worth up to $50 from lobbyists multiple times per year.",
  "The government spent $371,000 to study if mothers love dogs as much as kids.",
  "Congress members get free meals in the Senate dining room, subsidized by taxpayers.",
  "The IRS paid $60 million in bonuses to employees who owed back taxes.",
  "Politicians' pension plans are 5 times more generous than the average American's.",
  "The government spent $3 million to study hamster fighting (yes, seriously).",
  "Congress can override ethics violations with a simple majority vote.",
  "The federal government employs 15 different agencies to manage food safety for a single pizza.",
  "Politicians get free office supplies, postage, and travel even when campaigning.",
  "The government paid $2.6 million to teach Chinese prostitutes to drink responsibly.",
  "Congress members can accept all-expense-paid trips if they give a speech while there.",
  "The VA spent $6.1 million on sculptures and art while veterans waited months for care.",
  "Politicians can keep campaign donations even if they never run for office.",
  "The government spent $1.1 million to study the erectile dysfunction of obese men.",
  "Congress members get their own private gym that costs taxpayers $2 million per year.",
  "The federal government spent $400,000 studying gay hookup apps.",
  "Politicians can raise their own salaries without a public vote.",
  "The government paid $856,000 to teach mountain lions how to use treadmills.",
  "Congress exempted itself from workplace harassment laws until 1995.",
  "The IRS spent $50 million on employee conferences in just 3 years.",
  "Politicians get free printing, mailing, and photography services for 'official use'.",
  "The government spent $10 million on a Superman museum that was never built.",
  "Congress members can retire at age 50 with full benefits after 20 years of service.",
  "The federal government has 47 different job training programs across 9 agencies.",
  "Politicians can accept unlimited gifts from family members (who may have business interests).",
  "The government paid $765,000 to study if Neil Armstrong's 'one small step' quote was premeditated.",
  "Congress has its own exclusive health clinic with private doctors.",
  "The TSA spent $3,000 on a randomizer app to decide which line travelers go through.",
  "Politicians can use taxpayer money to fly first class on 'official business'.",
  "The government spent $147,000 to study the effect of cocaine on quail sexual behavior.",
  "Congress members pay reduced rates at the Capitol cafeteria, subsidized by taxpayers.",
  "The federal government has 80 different programs for helping the homeless but can't measure if any work.",
  "Politicians can accept campaign donations from foreign nationals through PACs.",
  "The government paid $1 million for a building in Afghanistan that was never used.",
  "Congress exempted itself from the Freedom of Information Act.",
  "The IRS paid $70 million in bonuses while cutting customer service.",
  "Politicians get free language lessons, fitness training, and career counseling.",
  "The government spent $500,000 to study if selfies make you happy (they don't).",
  "Congress members have access to insider stock tips through classified briefings.",
  "The federal government owns $1.4 billion in vacant or underutilized properties.",
  "Politicians can deduct their second home expenses if they claim it's for work.",
  "The government paid $615,000 to digitize Grateful Dead posters.",
  "Congress has a special dining room where meals cost $3 but are worth $15.",
  "The Pentagon spent $28 billion on uniforms that didn't work in combat.",
  "Politicians can accept honorariums of up to $2,000 for speeches to special interest groups.",
  "The government spent $466,000 to study if Twitter fights cause depression.",
  "Congress members get free reserved parking spaces worth $200,000 per year.",
  "The VA spent $20 million on solar panels that produce almost no electricity.",
  "Politicians can vote themselves pay raises during a government shutdown.",
  "The government paid $307,000 to study if Japanese quail are more promiscuous on cocaine.",
  "Congress has its own exclusive Capitol Hill Club with taxpayer subsidies.",
  "The IRS spent $60,000 on a single training video that was only 10 minutes long.",
  "Politicians get free legal defense for actions taken while in office.",
  "The government spent $1.2 million studying if old white men can trust young black men (actual study).",
  "Congress members can hire relatives as staffers and pay them with campaign funds.",
  "The federal government has 15,000 different IT systems that can't talk to each other.",
  "Politicians can convert campaign donations into retirement income through their PACs.",
  "The government paid $804,000 to study if people will eat food off the floor (5-second rule).",
  "Congress has its own exclusive hideaway offices that cost millions to maintain.",
  "The Pentagon spent $4.6 billion on planes that were immediately sent to the scrapyard.",
  "Politicians get free life insurance policies worth $174,000.",
  "The government spent $933,000 to discover that male fruit flies prefer younger females.",
  "Congress members can fly their spouses at government expense on 'fact-finding' trips.",
  "The IRS spent $4.1 million on a single IT contract that didn't work.",
  "Politicians can use official resources to write books and keep the royalties.",
  "The government paid $500,000 to study if people trust politicians more if they're attractive.",
  "Congress has special license plates that let them park illegally without tickets.",
  "The federal government spent $371,026 to study if mothers love dogs as much as children.",
  "Politicians can accept unlimited in-kind donations like private jet flights.",
  "The government spent $856,000 teaching mountain lions to use treadmills (worth repeating).",
  "Congress members get automatic cost-of-living raises tied to private sector wages.",
  "The Pentagon lost track of $6.5 trillion in accounting adjustments.",
  "Politicians can pocket excess campaign funds when they die (goes to their estate).",
  "The government paid $1.4 million to study if people relax more at vacation resorts than at home.",
  "Congress has its own exclusive gym, pool, and basketball court maintained by taxpayers.",
  "The IRS spent millions on bonuses for employees who didn't pay their own taxes.",
  "Politicians can accept book deals worth millions while in office.",
  "The government spent $2 million on a website that crashed on day one.",
  "Congress members can hire unlimited interns and pay them nothing (free labor).",
  "The federal government has 2,300 subsidy programs, most with no oversight.",
  "Politicians can trademark their names and profit from merchandise sales.",
  "The government paid $450,000 to study if men and women experience happiness differently.",
  "Congress gets free onsite medical care while cutting Medicare for seniors.",
  "The Pentagon bought 16,000 helicopters and has no idea where 6,000 of them are.",
  
  // Actually infuriating bullshit that makes you want to scream
  "Companies make you create an account just to view their website or download a PDF.",
  "Subscription services that make canceling 10x harder than signing up.",
  "Websites that force you to accept cookies or leave - there's no real choice.",
  "Job applications that make you upload a resume then manually re-type everything into boxes.",
  "Paying $200+ for concert tickets and $50 of it is 'service fees' for clicking a button.",
  "Cable companies that give new customers better deals than loyal customers who've paid for years.",
  "Printer ink costs more per ounce than human blood and champagne combined.",
  "Customer service that makes you wait 45 minutes just to tell you to 'restart your router'.",
  "Hospitals charge $20 for a single aspirin that costs 2 cents at the store.",
  "Airlines that charge $35 to check a bag but pack the plane so full carry-ons don't fit.",
  "Websites that detect ad blockers and block you from reading unless you turn it off.",
  "Getting spam emails from companies you never signed up for and unsubscribe does nothing.",
  "Apps that require access to your contacts, location, and camera just to use a flashlight.",
  "Tipping culture where employers don't pay workers and guilt customers into subsidizing wages.",
  "Banks that charge you a fee for not having enough money in your account.",
  "Textbooks that cost $400 and become worthless when they release a 'new edition' with one page changed.",
  "Phone plans that throttle your 'unlimited data' after you actually use it.",
  "Websites that make you disable your ad blocker but then show you malware ads.",
  "Credit card companies that drop your score for not using debt, but also for using too much debt.",
  "Landlords who raise rent every year but refuse to fix anything that's broken.",
  "Software that used to be free but now requires a $20/month subscription for the same features.",
  "Every device needing its own proprietary charger that costs $50 to replace.",
  "Grocery stores that demand your email, phone number, and zip code just to check out.",
  "Streaming services removing shows you paid to watch and offering no refund.",
  "Car dealerships adding $5,000 in 'market adjustment fees' on top of the sticker price.",
  "Apartment applications that charge $50-100 just to review your application (and still reject you).",
  "Companies that auto-renew subscriptions and make you call to cancel during business hours only.",
  "Health insurance that costs $500/month but has a $5,000 deductible before they pay anything.",
  "Websites that force you to create a password with 18 requirements then email it to you in plain text.",
  "TV remotes that need 3 different remotes to watch Netflix because of licensing bullshit.",
  "Paying for shipping both ways when returning a defective product you bought.",
  "Being put on hold for an hour only to be told 'our system is down, call back tomorrow'.",
  "Employers requiring 5 years experience for entry-level jobs that pay minimum wage.",
  "Social media apps that show you ads disguised as regular posts from your friends.",
  "ISPs that have data caps on home internet in 2025 when bandwidth is essentially free.",
  "Stores that ask for your email receipt and still print you a 3-foot long paper receipt.",
  "Apps that send push notifications every hour to remind you they exist.",
  "Credit bureaus that track your every purchase but you have to pay THEM to see your own credit report.",
  "Paying $1,000 for a phone that slows down after 2 years to make you buy a new one.",
  "Websites that reset your password for security then email you your new password in plain text.",
  "HOAs that fine you $500 for your grass being 1/4 inch too tall.",
  "Gyms that make you show up in person to cancel your membership but let you sign up online.",
  "Email newsletters with 'UNSUBSCRIBE' links that just take you to a page to manage preferences.",
  "Companies that make you sign arbitration agreements so you can't sue them when they screw you.",
  "Paying full price for games that are 'early access' aka unfinished broken garbage.",
  "Customer service bots that can't understand anything and won't let you talk to a human.",
  "Free trials that require a credit card and auto-charge you if you forget to cancel.",
  "Websites that force you to 'accept all cookies' or manually opt out of 500 individual tracking cookies.",
  "Getting charged a 'convenience fee' for paying your bill online instead of mailing a check.",
  "Pharmacies charging $300 for medication that costs $5 in every other country.",
  "Smart TVs that show you ads on the home screen of a TV you already bought.",
  "ISPs offering '1000 Mbps speeds' but it's only for downloads, uploads are still 10 Mbps.",
  "College parking passes that cost $500/year but there's never any parking available.",
  "Video games that cost $70 but have $200 worth of microtransactions and paid DLC.",
  "Restaurants automatically adding 20% gratuity then still showing you a tip line.",
  "Airlines overbooking flights and kicking paying customers off randomly.",
  "Software updates that reset all your preferences back to defaults.",
  "Paying for YouTube Premium and still seeing sponsor segments baked into videos.",
  "Getting robocalls about your car's extended warranty 5 times a day.",
  "Online shopping where the item costs $10 but shipping is $15.",
  "Password requirements so complex you have to write them down, defeating the security.",
  "Receipts that fade to blank in 6 months when you need to return something.",
  "Companies that say 'your call is very important to us' then put you on hold for 90 minutes.",
  "Paying a 'resort fee' at hotels that's not included in the room price they show online.",
  "Software that forces you to update before you can use it, and the update breaks everything.",
  "Uber surge pricing that charges you 5x during bad weather when you need it most.",
  "Apartment complexes charging $50/month for 'trash valet' that was included before.",
  "Email that says 'do not reply to this email' but doesn't tell you how to actually contact them.",
  "Apps that won't let you use them unless you rate 5 stars in the app store.",
  "Websites that block right-click and copy-paste to 'protect their content'.",
  "Getting charged a 'service fee' to pay a bill that's mandatory to pay anyway.",
  "Ticketmaster charging a $15 'print at home' fee for a ticket you print yourself.",
  "Companies that cancel your service for missing one payment but take 6 weeks to refund you.",
  "Social media algorithms that hide your friends' posts but show you ads constantly.",
  "Games that have loot boxes which are literally gambling marketed to children.",
  "Stores that make self-checkout then have an employee watching you use it anyway.",
  "Internet providers that throttle Netflix unless Netflix pays them extra.",
  "Paying $1,500 for a laptop with a keyboard that breaks from regular typing.",
  "Customer loyalty programs that require scanning an app that never works.",
  "Websites that won't let you paste into password fields 'for security'.",
  "Buying a $60 game that's just a live service platform for selling you more $20 cosmetics.",
  "Apartments that charge $75 'pest control fee' monthly but never actually spray for pests.",
  "Car insurance that goes up every year even if you've never had an accident.",
  "Stores that won't price match their own website price in the physical store.",
  "Software that requires internet connection to use even though it's installed on your computer.",
  "Getting spam texts about politics from numbers you can't block.",
  "Paying a 'delivery fee' plus tip but the driver still doesn't get the delivery fee.",
  "Companies that send you to collections over disputed bills without investigating.",
  "Apps that require location services to be on 24/7 or they won't work at all.",
  "Video streaming with unskippable 90-second ads on a service you're paying $15/month for.",
  "Parking meters that only take coins in 2025 when nobody carries cash.",
  "Getting 'pre-qualified' for a credit card then denied when you actually apply.",
  "Websites that remember your email but not your password, making you reset it every time.",
  "Being charged $150 to cancel a service because of a 2-year contract you didn't know about.",
  "Phone calls from scammers spoofing your area code so you think it's important.",
  "Companies that charge a 'paper statement fee' if you don't go paperless.",
  "Job interviews where they ghost you after 5 rounds and never give you any response.",
  "Mandatory tipping on takeout orders where there's literally no service.",
  "Paying $10/month for iCloud storage because they won't let you back up any other way.",
  "Websites that take your email 'for order updates' then spam you daily forever.",
  "Getting charged for doctor appointments you cancel but not refunded when they cancel on you.",
  "Apps that won't work unless you allow them to track you across other apps and websites.",
  "Paying full price to stream a movie but you can only rent it for 48 hours.",
  "Companies using 'inflation' as an excuse to raise prices 30% when inflation is 3%.",
];

const BullshitFact: React.FC = () => {
  const [currentFact, setCurrentFact] = useState('');
  const [isAnimating, setIsAnimating] = useState(false);

  const getRandomFact = () => {
    const randomIndex = Math.floor(Math.random() * facts.length);
    return facts[randomIndex];
  };

  const rotateFact = () => {
    setIsAnimating(true);
    setTimeout(() => {
      setCurrentFact(getRandomFact());
      setIsAnimating(false);
    }, 500);
  };

  useEffect(() => {
    setCurrentFact(getRandomFact());
    
    // Rotate fact every 10 seconds
    const interval = setInterval(rotateFact, 10000);
    
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="bullshit-fact">
      <div className="fact-header">💩 BULLSHIT FACT 💩</div>
      <div className={`fact-content ${isAnimating ? 'fade-out' : 'fade-in'}`}>
        {currentFact}
      </div>
    </div>
  );
};

export default BullshitFact;
